#!/bin/bash
DIRECTORY=./inc/boldgrid-theme-framework
BRANCH=dev
if [ -d "$DIRECTORY" ]; then
	rm -rf $DIRECTORY
fi
git clone -b ${1:-$BRANCH} --single-branch https://github.com/BoldGrid/boldgrid-theme-framework.git $DIRECTORY
cd $DIRECTORY && git filter-branch --subdirectory-filter $(basename $DIRECTORY) && rm -rf .git
